pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '/usr/local/maven/bin/mvn -B -DskipTests -Dcolor=false clean package'
            }
        }
        stage('Test') {
            steps {
                sh '/usr/local/maven/bin/mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Run Application') {
            steps {
                sh 'java -jar "target/my-app-1.0-SNAPSHOT.jar"'
            }
        }
    }
}
